package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import service.MembershipService;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @program: src
 * @description:
 * @create: 2020-04-12 18:01
 **/

public class AccountGUI {
    private JFrame frame;
    private JPanel accountPanel;
    private JTextField fNTextField;
    private JTextField lNTextField;
    private JTextField emailTextField;
    private JTextField telTextField;
    private JTextField stampsTextField;
    private JButton backButton;
    private JButton subscribeButton;
    private JButton modifyButton;
    private JLabel accountLabel;
    private JLabel fNLabel;
    private JLabel lNLabel;
    private JLabel emailLabel;
    private JLabel telLabel;
    private JLabel stampsLabel;
    private JTextField IdTextField;
    private JLabel IdLabel;
    private String[] choices;

    public AccountGUI(final String[] choices) {
        this.choices = choices;

        $$$setupUI$$$();
        backButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                frame.dispose();
                ConfirmGUI.main(choices);
            }
        });
    }

    public static void main(String[] args) {
        AccountGUI account = new AccountGUI(args);
        account.frame = new JFrame("Account");
        account.frame.setContentPane(account.accountPanel);
        account.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        account.frame.pack();
        account.frame.setSize(800, 600);
        account.frame.setLocationRelativeTo(null);
        account.frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        MembershipService member = new MembershipService();
        String[] info = member.getInfo(choices[12].substring(0, 8));
        fNTextField = new JTextField();
        fNTextField.setBorder(new EmptyBorder(0, 0, 0, 0));
        fNTextField.setText(info[0]);
        lNTextField = new JTextField();
        lNTextField.setBorder(new EmptyBorder(0, 0, 0, 0));
        lNTextField.setText(info[1]);
        emailTextField = new JTextField();
        emailTextField.setBorder(new EmptyBorder(0, 0, 0, 0));
        if (info[2] == null) {
            info[2] = "Not Set";
        }
        emailTextField.setText(info[2]);
        telTextField = new JTextField();
        telTextField.setBorder(new EmptyBorder(0, 0, 0, 0));
        if (info[3] == null) {
            info[3] = "Not Set";
        }
        telTextField.setText(info[3]);
        IdTextField = new JTextField();
        IdTextField.setBorder(new EmptyBorder(0, 0, 0, 0));
        IdTextField.setText(info[4]);
        stampsTextField = new JTextField();
        stampsTextField.setBorder(new EmptyBorder(0, 0, 0, 0));
        stampsTextField.setText(info[5]);

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        accountPanel = new JPanel();
        accountPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 3, new Insets(5, 15, 15, 15), -1, -1));
        accountPanel.setBackground(new Color(-721665));
        Font accountPanelFont = this.$$$getFont$$$(null, Font.BOLD, 28, accountPanel.getFont());
        if (accountPanelFont != null) accountPanel.setFont(accountPanelFont);
        accountPanel.setForeground(new Color(-15132391));
        accountLabel = new JLabel();
        Font accountLabelFont = this.$$$getFont$$$(null, Font.BOLD, 28, accountLabel.getFont());
        if (accountLabelFont != null) accountLabel.setFont(accountLabelFont);
        accountLabel.setForeground(new Color(-15132391));
        accountLabel.setText("My Account");
        accountPanel.add(accountLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        fNLabel = new JLabel();
        fNLabel.setBackground(new Color(-721665));
        Font fNLabelFont = this.$$$getFont$$$(null, Font.BOLD, 20, fNLabel.getFont());
        if (fNLabelFont != null) fNLabel.setFont(fNLabelFont);
        fNLabel.setForeground(new Color(-15132391));
        fNLabel.setText("First Name");
        accountPanel.add(fNLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        fNTextField.setBackground(new Color(-1642256));
        fNTextField.setEditable(false);
        Font fNTextFieldFont = this.$$$getFont$$$(null, -1, 20, fNTextField.getFont());
        if (fNTextFieldFont != null) fNTextField.setFont(fNTextFieldFont);
        fNTextField.setForeground(new Color(-15132391));
        accountPanel.add(fNTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
        lNLabel = new JLabel();
        lNLabel.setBackground(new Color(-721665));
        Font lNLabelFont = this.$$$getFont$$$(null, Font.BOLD, 20, lNLabel.getFont());
        if (lNLabelFont != null) lNLabel.setFont(lNLabelFont);
        lNLabel.setForeground(new Color(-15132391));
        lNLabel.setText("Last Name");
        accountPanel.add(lNLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lNTextField.setBackground(new Color(-1642256));
        lNTextField.setEditable(false);
        Font lNTextFieldFont = this.$$$getFont$$$(null, -1, 20, lNTextField.getFont());
        if (lNTextFieldFont != null) lNTextField.setFont(lNTextFieldFont);
        lNTextField.setForeground(new Color(-15132391));
        accountPanel.add(lNTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
        emailLabel = new JLabel();
        emailLabel.setBackground(new Color(-721665));
        Font emailLabelFont = this.$$$getFont$$$(null, Font.BOLD, 20, emailLabel.getFont());
        if (emailLabelFont != null) emailLabel.setFont(emailLabelFont);
        emailLabel.setForeground(new Color(-15132391));
        emailLabel.setText("Email");
        accountPanel.add(emailLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        emailTextField.setBackground(new Color(-1642256));
        emailTextField.setEditable(false);
        Font emailTextFieldFont = this.$$$getFont$$$(null, -1, 20, emailTextField.getFont());
        if (emailTextFieldFont != null) emailTextField.setFont(emailTextFieldFont);
        emailTextField.setForeground(new Color(-15132391));
        accountPanel.add(emailTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
        telLabel = new JLabel();
        telLabel.setBackground(new Color(-721665));
        Font telLabelFont = this.$$$getFont$$$(null, Font.BOLD, 20, telLabel.getFont());
        if (telLabelFont != null) telLabel.setFont(telLabelFont);
        telLabel.setForeground(new Color(-15132391));
        telLabel.setText("Mobile Number");
        accountPanel.add(telLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        telTextField.setBackground(new Color(-1642256));
        telTextField.setEditable(false);
        Font telTextFieldFont = this.$$$getFont$$$(null, -1, 20, telTextField.getFont());
        if (telTextFieldFont != null) telTextField.setFont(telTextFieldFont);
        telTextField.setForeground(new Color(-15132391));
        accountPanel.add(telTextField, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
        stampsLabel = new JLabel();
        stampsLabel.setBackground(new Color(-721665));
        Font stampsLabelFont = this.$$$getFont$$$(null, Font.BOLD, 20, stampsLabel.getFont());
        if (stampsLabelFont != null) stampsLabel.setFont(stampsLabelFont);
        stampsLabel.setForeground(new Color(-15132391));
        stampsLabel.setText("Virtual Stamps");
        accountPanel.add(stampsLabel, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        stampsTextField.setBackground(new Color(-1642256));
        stampsTextField.setEditable(false);
        Font stampsTextFieldFont = this.$$$getFont$$$(null, -1, 20, stampsTextField.getFont());
        if (stampsTextFieldFont != null) stampsTextField.setFont(stampsTextFieldFont);
        stampsTextField.setForeground(new Color(-15132391));
        accountPanel.add(stampsTextField, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
        backButton = new JButton();
        backButton.setBackground(new Color(-1642256));
        Font backButtonFont = this.$$$getFont$$$(null, Font.BOLD, 20, backButton.getFont());
        if (backButtonFont != null) backButton.setFont(backButtonFont);
        backButton.setForeground(new Color(-15132391));
        backButton.setText("Back to Payment");
        accountPanel.add(backButton, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        subscribeButton = new JButton();
        subscribeButton.setBackground(new Color(-1642256));
        Font subscribeButtonFont = this.$$$getFont$$$(null, Font.BOLD, 20, subscribeButton.getFont());
        if (subscribeButtonFont != null) subscribeButton.setFont(subscribeButtonFont);
        subscribeButton.setForeground(new Color(-15132391));
        subscribeButton.setText("Subscribe");
        accountPanel.add(subscribeButton, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        modifyButton = new JButton();
        modifyButton.setBackground(new Color(-1642256));
        Font modifyButtonFont = this.$$$getFont$$$(null, Font.BOLD, 20, modifyButton.getFont());
        if (modifyButtonFont != null) modifyButton.setFont(modifyButtonFont);
        modifyButton.setForeground(new Color(-15132391));
        modifyButton.setText("Modify");
        accountPanel.add(modifyButton, new com.intellij.uiDesigner.core.GridConstraints(7, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        IdLabel = new JLabel();
        IdLabel.setBackground(new Color(-721665));
        Font IdLabelFont = this.$$$getFont$$$(null, Font.BOLD, 20, IdLabel.getFont());
        if (IdLabelFont != null) IdLabel.setFont(IdLabelFont);
        IdLabel.setForeground(new Color(-15132391));
        IdLabel.setText("Membership Id");
        accountPanel.add(IdLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        IdTextField.setBackground(new Color(-1642256));
        IdTextField.setEditable(false);
        Font IdTextFieldFont = this.$$$getFont$$$(null, -1, 20, IdTextField.getFont());
        if (IdTextFieldFont != null) IdTextField.setFont(IdTextFieldFont);
        IdTextField.setForeground(new Color(-15132391));
        accountPanel.add(IdTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 5, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return accountPanel;
    }
}
